// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feeders.proto

package edu.usf.ratsim.robot.ssl.sensefeeder.protobuf;

public final class FeedersOuterClass {
  private FeedersOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FeederOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Feeder)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required float x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 2;</code>
     */
    float getX();

    /**
     * <code>required float y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 3;</code>
     */
    float getY();
  }
  /**
   * Protobuf type {@code Feeder}
   */
  public static final class Feeder extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Feeder)
      FeederOrBuilder {
    // Use Feeder.newBuilder() to construct.
    private Feeder(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Feeder(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Feeder defaultInstance;
    public static Feeder getDefaultInstance() {
      return defaultInstance;
    }

    public Feeder getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Feeder(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              x_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              y_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeder_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.class, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder.class);
    }

    public static com.google.protobuf.Parser<Feeder> PARSER =
        new com.google.protobuf.AbstractParser<Feeder>() {
      public Feeder parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Feeder(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Feeder> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    /**
     * <code>required float x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float x = 2;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private float y_;
    /**
     * <code>required float y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float y = 3;</code>
     */
    public float getY() {
      return y_;
    }

    private void initFields() {
      id_ = 0;
      x_ = 0F;
      y_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, y_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Feeder}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Feeder)
        edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeder_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeder_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.class, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder.class);
      }

      // Construct using edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeder_descriptor;
      }

      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder getDefaultInstanceForType() {
        return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.getDefaultInstance();
      }

      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder build() {
        edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder buildPartial() {
        edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder result = new edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder) {
          return mergeFrom((edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder other) {
        if (other == edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private float x_ ;
      /**
       * <code>required float x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float x = 2;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float y = 3;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 3;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Feeder)
    }

    static {
      defaultInstance = new Feeder(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Feeder)
  }

  public interface FeedersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Feeders)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    java.util.List<edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder> 
        getFeedersList();
    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder getFeeders(int index);
    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    int getFeedersCount();
    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    java.util.List<? extends edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder> 
        getFeedersOrBuilderList();
    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder getFeedersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Feeders}
   */
  public static final class Feeders extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Feeders)
      FeedersOrBuilder {
    // Use Feeders.newBuilder() to construct.
    private Feeders(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Feeders(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Feeders defaultInstance;
    public static Feeders getDefaultInstance() {
      return defaultInstance;
    }

    public Feeders getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Feeders(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                feeders_ = new java.util.ArrayList<edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder>();
                mutable_bitField0_ |= 0x00000001;
              }
              feeders_.add(input.readMessage(edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          feeders_ = java.util.Collections.unmodifiableList(feeders_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeders_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeders_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders.class, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders.Builder.class);
    }

    public static com.google.protobuf.Parser<Feeders> PARSER =
        new com.google.protobuf.AbstractParser<Feeders>() {
      public Feeders parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Feeders(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Feeders> getParserForType() {
      return PARSER;
    }

    public static final int FEEDERS_FIELD_NUMBER = 1;
    private java.util.List<edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder> feeders_;
    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    public java.util.List<edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder> getFeedersList() {
      return feeders_;
    }
    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    public java.util.List<? extends edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder> 
        getFeedersOrBuilderList() {
      return feeders_;
    }
    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    public int getFeedersCount() {
      return feeders_.size();
    }
    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder getFeeders(int index) {
      return feeders_.get(index);
    }
    /**
     * <code>repeated .Feeder feeders = 1;</code>
     */
    public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder getFeedersOrBuilder(
        int index) {
      return feeders_.get(index);
    }

    private void initFields() {
      feeders_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getFeedersCount(); i++) {
        if (!getFeeders(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < feeders_.size(); i++) {
        output.writeMessage(1, feeders_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < feeders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, feeders_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Feeders}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Feeders)
        edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeedersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeders_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeders_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders.class, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders.Builder.class);
      }

      // Construct using edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFeedersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (feedersBuilder_ == null) {
          feeders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          feedersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.internal_static_Feeders_descriptor;
      }

      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders getDefaultInstanceForType() {
        return edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders.getDefaultInstance();
      }

      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders build() {
        edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders buildPartial() {
        edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders result = new edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders(this);
        int from_bitField0_ = bitField0_;
        if (feedersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            feeders_ = java.util.Collections.unmodifiableList(feeders_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.feeders_ = feeders_;
        } else {
          result.feeders_ = feedersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders) {
          return mergeFrom((edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders other) {
        if (other == edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders.getDefaultInstance()) return this;
        if (feedersBuilder_ == null) {
          if (!other.feeders_.isEmpty()) {
            if (feeders_.isEmpty()) {
              feeders_ = other.feeders_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFeedersIsMutable();
              feeders_.addAll(other.feeders_);
            }
            onChanged();
          }
        } else {
          if (!other.feeders_.isEmpty()) {
            if (feedersBuilder_.isEmpty()) {
              feedersBuilder_.dispose();
              feedersBuilder_ = null;
              feeders_ = other.feeders_;
              bitField0_ = (bitField0_ & ~0x00000001);
              feedersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFeedersFieldBuilder() : null;
            } else {
              feedersBuilder_.addAllMessages(other.feeders_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getFeedersCount(); i++) {
          if (!getFeeders(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeders) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder> feeders_ =
        java.util.Collections.emptyList();
      private void ensureFeedersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          feeders_ = new java.util.ArrayList<edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder>(feeders_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder> feedersBuilder_;

      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public java.util.List<edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder> getFeedersList() {
        if (feedersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(feeders_);
        } else {
          return feedersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public int getFeedersCount() {
        if (feedersBuilder_ == null) {
          return feeders_.size();
        } else {
          return feedersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder getFeeders(int index) {
        if (feedersBuilder_ == null) {
          return feeders_.get(index);
        } else {
          return feedersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public Builder setFeeders(
          int index, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder value) {
        if (feedersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeedersIsMutable();
          feeders_.set(index, value);
          onChanged();
        } else {
          feedersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public Builder setFeeders(
          int index, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder builderForValue) {
        if (feedersBuilder_ == null) {
          ensureFeedersIsMutable();
          feeders_.set(index, builderForValue.build());
          onChanged();
        } else {
          feedersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public Builder addFeeders(edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder value) {
        if (feedersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeedersIsMutable();
          feeders_.add(value);
          onChanged();
        } else {
          feedersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public Builder addFeeders(
          int index, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder value) {
        if (feedersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeedersIsMutable();
          feeders_.add(index, value);
          onChanged();
        } else {
          feedersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public Builder addFeeders(
          edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder builderForValue) {
        if (feedersBuilder_ == null) {
          ensureFeedersIsMutable();
          feeders_.add(builderForValue.build());
          onChanged();
        } else {
          feedersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public Builder addFeeders(
          int index, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder builderForValue) {
        if (feedersBuilder_ == null) {
          ensureFeedersIsMutable();
          feeders_.add(index, builderForValue.build());
          onChanged();
        } else {
          feedersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public Builder addAllFeeders(
          java.lang.Iterable<? extends edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder> values) {
        if (feedersBuilder_ == null) {
          ensureFeedersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, feeders_);
          onChanged();
        } else {
          feedersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public Builder clearFeeders() {
        if (feedersBuilder_ == null) {
          feeders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          feedersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public Builder removeFeeders(int index) {
        if (feedersBuilder_ == null) {
          ensureFeedersIsMutable();
          feeders_.remove(index);
          onChanged();
        } else {
          feedersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder getFeedersBuilder(
          int index) {
        return getFeedersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder getFeedersOrBuilder(
          int index) {
        if (feedersBuilder_ == null) {
          return feeders_.get(index);  } else {
          return feedersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public java.util.List<? extends edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder> 
           getFeedersOrBuilderList() {
        if (feedersBuilder_ != null) {
          return feedersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(feeders_);
        }
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder addFeedersBuilder() {
        return getFeedersFieldBuilder().addBuilder(
            edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.getDefaultInstance());
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder addFeedersBuilder(
          int index) {
        return getFeedersFieldBuilder().addBuilder(
            index, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.getDefaultInstance());
      }
      /**
       * <code>repeated .Feeder feeders = 1;</code>
       */
      public java.util.List<edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder> 
           getFeedersBuilderList() {
        return getFeedersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder> 
          getFeedersFieldBuilder() {
        if (feedersBuilder_ == null) {
          feedersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.Feeder.Builder, edu.usf.ratsim.robot.ssl.sensefeeder.protobuf.FeedersOuterClass.FeederOrBuilder>(
                  feeders_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          feeders_ = null;
        }
        return feedersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Feeders)
    }

    static {
      defaultInstance = new Feeders(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Feeders)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Feeder_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Feeder_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Feeders_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Feeders_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rfeeders.proto\"*\n\006Feeder\022\n\n\002id\030\001 \002(\005\022\t\n" +
      "\001x\030\002 \002(\002\022\t\n\001y\030\003 \002(\002\"#\n\007Feeders\022\030\n\007feeder" +
      "s\030\001 \003(\0132\007.FeederB/\n-edu.usf.ratsim.robot" +
      ".ssl.sensefeeder.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Feeder_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Feeder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Feeder_descriptor,
        new java.lang.String[] { "Id", "X", "Y", });
    internal_static_Feeders_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Feeders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Feeders_descriptor,
        new java.lang.String[] { "Feeders", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
