// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slamstate.proto

package edu.usf.ratsim.robot.ssl.slam.protobuf;

public final class Slamstate {
  private Slamstate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SlamStateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 state = 1;
    /**
     * <code>required int32 state = 1;</code>
     */
    boolean hasState();
    /**
     * <code>required int32 state = 1;</code>
     */
    int getState();

    // required float x = 2;
    /**
     * <code>required float x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 2;</code>
     */
    float getX();

    // required float y = 3;
    /**
     * <code>required float y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 3;</code>
     */
    float getY();

    // required float heading = 4;
    /**
     * <code>required float heading = 4;</code>
     */
    boolean hasHeading();
    /**
     * <code>required float heading = 4;</code>
     */
    float getHeading();
  }
  /**
   * Protobuf type {@code SlamState}
   */
  public static final class SlamState extends
      com.google.protobuf.GeneratedMessage
      implements SlamStateOrBuilder {
    // Use SlamState.newBuilder() to construct.
    private SlamState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SlamState(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SlamState defaultInstance;
    public static SlamState getDefaultInstance() {
      return defaultInstance;
    }

    public SlamState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SlamState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              state_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              x_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              y_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              heading_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.internal_static_SlamState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.internal_static_SlamState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState.class, edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState.Builder.class);
    }

    public static com.google.protobuf.Parser<SlamState> PARSER =
        new com.google.protobuf.AbstractParser<SlamState>() {
      public SlamState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SlamState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SlamState> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 state = 1;
    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <code>required int32 state = 1;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 state = 1;</code>
     */
    public int getState() {
      return state_;
    }

    // required float x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    /**
     * <code>required float x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float x = 2;</code>
     */
    public float getX() {
      return x_;
    }

    // required float y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private float y_;
    /**
     * <code>required float y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float y = 3;</code>
     */
    public float getY() {
      return y_;
    }

    // required float heading = 4;
    public static final int HEADING_FIELD_NUMBER = 4;
    private float heading_;
    /**
     * <code>required float heading = 4;</code>
     */
    public boolean hasHeading() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float heading = 4;</code>
     */
    public float getHeading() {
      return heading_;
    }

    private void initFields() {
      state_ = 0;
      x_ = 0F;
      y_ = 0F;
      heading_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeading()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, heading_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, heading_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SlamState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.internal_static_SlamState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.internal_static_SlamState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState.class, edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState.Builder.class);
      }

      // Construct using edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        heading_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.internal_static_SlamState_descriptor;
      }

      public edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState getDefaultInstanceForType() {
        return edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState.getDefaultInstance();
      }

      public edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState build() {
        edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState buildPartial() {
        edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState result = new edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.heading_ = heading_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState) {
          return mergeFrom((edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState other) {
        if (other == edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasHeading()) {
          setHeading(other.getHeading());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasState()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasHeading()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usf.ratsim.robot.ssl.slam.protobuf.Slamstate.SlamState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 state = 1;
      private int state_ ;
      /**
       * <code>required int32 state = 1;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 state = 1;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>required int32 state = 1;</code>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 state = 1;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        onChanged();
        return this;
      }

      // required float x = 2;
      private float x_ ;
      /**
       * <code>required float x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float x = 2;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        onChanged();
        return this;
      }

      // required float y = 3;
      private float y_ ;
      /**
       * <code>required float y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float y = 3;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 3;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        onChanged();
        return this;
      }

      // required float heading = 4;
      private float heading_ ;
      /**
       * <code>required float heading = 4;</code>
       */
      public boolean hasHeading() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float heading = 4;</code>
       */
      public float getHeading() {
        return heading_;
      }
      /**
       * <code>required float heading = 4;</code>
       */
      public Builder setHeading(float value) {
        bitField0_ |= 0x00000008;
        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float heading = 4;</code>
       */
      public Builder clearHeading() {
        bitField0_ = (bitField0_ & ~0x00000008);
        heading_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SlamState)
    }

    static {
      defaultInstance = new SlamState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SlamState)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SlamState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SlamState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017slamstate.proto\"A\n\tSlamState\022\r\n\005state\030" +
      "\001 \002(\005\022\t\n\001x\030\002 \002(\002\022\t\n\001y\030\003 \002(\002\022\017\n\007heading\030\004" +
      " \002(\002B(\n&edu.usf.ratsim.robot.ssl.slam.pr" +
      "otobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SlamState_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SlamState_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SlamState_descriptor,
              new java.lang.String[] { "State", "X", "Y", "Heading", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
