// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package edu.usf.ratsim.robot.naorobot.protobuf;

public final class Connector {
  private Connector() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .Command.CommandType type = 1 [default = getInfo];
    /**
     * <code>optional .Command.CommandType type = 1 [default = getInfo];</code>
     */
    boolean hasType();
    /**
     * <code>optional .Command.CommandType type = 1 [default = getInfo];</code>
     */
    edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType getType();

    // optional float angle = 2;
    /**
     * <code>optional float angle = 2;</code>
     */
    boolean hasAngle();
    /**
     * <code>optional float angle = 2;</code>
     */
    float getAngle();
  }
  /**
   * Protobuf type {@code Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }

    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType value = edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              angle_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.class, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.Builder.class);
    }

    public static com.google.protobuf.Parser<Command> PARSER =
        new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Command.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>doAction = 0;</code>
       */
      doAction(0, 0),
      /**
       * <code>rotate = 1;</code>
       */
      rotate(1, 1),
      /**
       * <code>getInfo = 2;</code>
       */
      getInfo(2, 2),
      /**
       * <code>startRobot = 3;</code>
       */
      startRobot(3, 3),
      /**
       * <code>stopRobot = 4;</code>
       */
      stopRobot(4, 4),
      ;

      /**
       * <code>doAction = 0;</code>
       */
      public static final int doAction_VALUE = 0;
      /**
       * <code>rotate = 1;</code>
       */
      public static final int rotate_VALUE = 1;
      /**
       * <code>getInfo = 2;</code>
       */
      public static final int getInfo_VALUE = 2;
      /**
       * <code>startRobot = 3;</code>
       */
      public static final int startRobot_VALUE = 3;
      /**
       * <code>stopRobot = 4;</code>
       */
      public static final int stopRobot_VALUE = 4;


      public final int getNumber() { return value; }

      public static CommandType valueOf(int value) {
        switch (value) {
          case 0: return doAction;
          case 1: return rotate;
          case 2: return getInfo;
          case 3: return startRobot;
          case 4: return stopRobot;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CommandType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Command.CommandType)
    }

    private int bitField0_;
    // optional .Command.CommandType type = 1 [default = getInfo];
    public static final int TYPE_FIELD_NUMBER = 1;
    private edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType type_;
    /**
     * <code>optional .Command.CommandType type = 1 [default = getInfo];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Command.CommandType type = 1 [default = getInfo];</code>
     */
    public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType getType() {
      return type_;
    }

    // optional float angle = 2;
    public static final int ANGLE_FIELD_NUMBER = 2;
    private float angle_;
    /**
     * <code>optional float angle = 2;</code>
     */
    public boolean hasAngle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float angle = 2;</code>
     */
    public float getAngle() {
      return angle_;
    }

    private void initFields() {
      type_ = edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType.getInfo;
      angle_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, angle_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, angle_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.usf.ratsim.robot.naorobot.protobuf.Connector.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.class, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.Builder.class);
      }

      // Construct using edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType.getInfo;
        bitField0_ = (bitField0_ & ~0x00000001);
        angle_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Command_descriptor;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command getDefaultInstanceForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.getDefaultInstance();
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command build() {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command buildPartial() {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command result = new edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.angle_ = angle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command) {
          return mergeFrom((edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command other) {
        if (other == edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAngle()) {
          setAngle(other.getAngle());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .Command.CommandType type = 1 [default = getInfo];
      private edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType type_ = edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType.getInfo;
      /**
       * <code>optional .Command.CommandType type = 1 [default = getInfo];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Command.CommandType type = 1 [default = getInfo];</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType getType() {
        return type_;
      }
      /**
       * <code>optional .Command.CommandType type = 1 [default = getInfo];</code>
       */
      public Builder setType(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Command.CommandType type = 1 [default = getInfo];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = edu.usf.ratsim.robot.naorobot.protobuf.Connector.Command.CommandType.getInfo;
        onChanged();
        return this;
      }

      // optional float angle = 2;
      private float angle_ ;
      /**
       * <code>optional float angle = 2;</code>
       */
      public boolean hasAngle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float angle = 2;</code>
       */
      public float getAngle() {
        return angle_;
      }
      /**
       * <code>optional float angle = 2;</code>
       */
      public Builder setAngle(float value) {
        bitField0_ |= 0x00000002;
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float angle = 2;</code>
       */
      public Builder clearAngle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        angle_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Command)
    }

    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Command)
  }

  public interface LandmarkOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required float x = 2;
    /**
     * <code>required float x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 2;</code>
     */
    float getX();

    // required float y = 3;
    /**
     * <code>required float y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 3;</code>
     */
    float getY();

    // required float z = 4;
    /**
     * <code>required float z = 4;</code>
     */
    boolean hasZ();
    /**
     * <code>required float z = 4;</code>
     */
    float getZ();
  }
  /**
   * Protobuf type {@code Landmark}
   */
  public static final class Landmark extends
      com.google.protobuf.GeneratedMessage
      implements LandmarkOrBuilder {
    // Use Landmark.newBuilder() to construct.
    private Landmark(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Landmark(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Landmark defaultInstance;
    public static Landmark getDefaultInstance() {
      return defaultInstance;
    }

    public Landmark getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Landmark(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              x_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              y_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              z_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Landmark_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Landmark_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.class, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder.class);
    }

    public static com.google.protobuf.Parser<Landmark> PARSER =
        new com.google.protobuf.AbstractParser<Landmark>() {
      public Landmark parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Landmark(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Landmark> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required float x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    /**
     * <code>required float x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float x = 2;</code>
     */
    public float getX() {
      return x_;
    }

    // required float y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private float y_;
    /**
     * <code>required float y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float y = 3;</code>
     */
    public float getY() {
      return y_;
    }

    // required float z = 4;
    public static final int Z_FIELD_NUMBER = 4;
    private float z_;
    /**
     * <code>required float z = 4;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float z = 4;</code>
     */
    public float getZ() {
      return z_;
    }

    private void initFields() {
      id_ = 0;
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, z_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Landmark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Landmark_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Landmark_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.class, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder.class);
      }

      // Construct using edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Landmark_descriptor;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark getDefaultInstanceForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.getDefaultInstance();
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark build() {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark buildPartial() {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark result = new edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark) {
          return mergeFrom((edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark other) {
        if (other == edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasZ()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required float x = 2;
      private float x_ ;
      /**
       * <code>required float x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float x = 2;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        onChanged();
        return this;
      }

      // required float y = 3;
      private float y_ ;
      /**
       * <code>required float y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float y = 3;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 3;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        onChanged();
        return this;
      }

      // required float z = 4;
      private float z_ ;
      /**
       * <code>required float z = 4;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float z = 4;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>required float z = 4;</code>
       */
      public Builder setZ(float value) {
        bitField0_ |= 0x00000008;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float z = 4;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        z_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Landmark)
    }

    static {
      defaultInstance = new Landmark(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Landmark)
  }

  public interface AffordancesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated bool aff = 1;
    /**
     * <code>repeated bool aff = 1;</code>
     */
    java.util.List<java.lang.Boolean> getAffList();
    /**
     * <code>repeated bool aff = 1;</code>
     */
    int getAffCount();
    /**
     * <code>repeated bool aff = 1;</code>
     */
    boolean getAff(int index);
  }
  /**
   * Protobuf type {@code Affordances}
   */
  public static final class Affordances extends
      com.google.protobuf.GeneratedMessage
      implements AffordancesOrBuilder {
    // Use Affordances.newBuilder() to construct.
    private Affordances(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Affordances(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Affordances defaultInstance;
    public static Affordances getDefaultInstance() {
      return defaultInstance;
    }

    public Affordances getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Affordances(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                aff_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000001;
              }
              aff_.add(input.readBool());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                aff_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                aff_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          aff_ = java.util.Collections.unmodifiableList(aff_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Affordances_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Affordances_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.class, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.Builder.class);
    }

    public static com.google.protobuf.Parser<Affordances> PARSER =
        new com.google.protobuf.AbstractParser<Affordances>() {
      public Affordances parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Affordances(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Affordances> getParserForType() {
      return PARSER;
    }

    // repeated bool aff = 1;
    public static final int AFF_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Boolean> aff_;
    /**
     * <code>repeated bool aff = 1;</code>
     */
    public java.util.List<java.lang.Boolean>
        getAffList() {
      return aff_;
    }
    /**
     * <code>repeated bool aff = 1;</code>
     */
    public int getAffCount() {
      return aff_.size();
    }
    /**
     * <code>repeated bool aff = 1;</code>
     */
    public boolean getAff(int index) {
      return aff_.get(index);
    }

    private void initFields() {
      aff_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < aff_.size(); i++) {
        output.writeBool(1, aff_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 1 * getAffList().size();
        size += dataSize;
        size += 1 * getAffList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Affordances}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.usf.ratsim.robot.naorobot.protobuf.Connector.AffordancesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Affordances_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Affordances_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.class, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.Builder.class);
      }

      // Construct using edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        aff_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Affordances_descriptor;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances getDefaultInstanceForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.getDefaultInstance();
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances build() {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances buildPartial() {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances result = new edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          aff_ = java.util.Collections.unmodifiableList(aff_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.aff_ = aff_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances) {
          return mergeFrom((edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances other) {
        if (other == edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.getDefaultInstance()) return this;
        if (!other.aff_.isEmpty()) {
          if (aff_.isEmpty()) {
            aff_ = other.aff_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAffIsMutable();
            aff_.addAll(other.aff_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bool aff = 1;
      private java.util.List<java.lang.Boolean> aff_ = java.util.Collections.emptyList();
      private void ensureAffIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          aff_ = new java.util.ArrayList<java.lang.Boolean>(aff_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bool aff = 1;</code>
       */
      public java.util.List<java.lang.Boolean>
          getAffList() {
        return java.util.Collections.unmodifiableList(aff_);
      }
      /**
       * <code>repeated bool aff = 1;</code>
       */
      public int getAffCount() {
        return aff_.size();
      }
      /**
       * <code>repeated bool aff = 1;</code>
       */
      public boolean getAff(int index) {
        return aff_.get(index);
      }
      /**
       * <code>repeated bool aff = 1;</code>
       */
      public Builder setAff(
          int index, boolean value) {
        ensureAffIsMutable();
        aff_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool aff = 1;</code>
       */
      public Builder addAff(boolean value) {
        ensureAffIsMutable();
        aff_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool aff = 1;</code>
       */
      public Builder addAllAff(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureAffIsMutable();
        super.addAll(values, aff_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool aff = 1;</code>
       */
      public Builder clearAff() {
        aff_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Affordances)
    }

    static {
      defaultInstance = new Affordances(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Affordances)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool ok = 1;
    /**
     * <code>required bool ok = 1;</code>
     */
    boolean hasOk();
    /**
     * <code>required bool ok = 1;</code>
     */
    boolean getOk();

    // repeated .Landmark landmarks = 2;
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark> 
        getLandmarksList();
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark getLandmarks(int index);
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    int getLandmarksCount();
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    java.util.List<? extends edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder> 
        getLandmarksOrBuilderList();
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder getLandmarksOrBuilder(
        int index);

    // optional .Affordances affs = 3;
    /**
     * <code>optional .Affordances affs = 3;</code>
     */
    boolean hasAffs();
    /**
     * <code>optional .Affordances affs = 3;</code>
     */
    edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances getAffs();
    /**
     * <code>optional .Affordances affs = 3;</code>
     */
    edu.usf.ratsim.robot.naorobot.protobuf.Connector.AffordancesOrBuilder getAffsOrBuilder();
  }
  /**
   * Protobuf type {@code Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ok_ = input.readBool();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                landmarks_ = new java.util.ArrayList<edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark>();
                mutable_bitField0_ |= 0x00000002;
              }
              landmarks_.add(input.readMessage(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = affs_.toBuilder();
              }
              affs_ = input.readMessage(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(affs_);
                affs_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          landmarks_ = java.util.Collections.unmodifiableList(landmarks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response.class, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool ok = 1;
    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <code>required bool ok = 1;</code>
     */
    public boolean hasOk() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool ok = 1;</code>
     */
    public boolean getOk() {
      return ok_;
    }

    // repeated .Landmark landmarks = 2;
    public static final int LANDMARKS_FIELD_NUMBER = 2;
    private java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark> landmarks_;
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    public java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark> getLandmarksList() {
      return landmarks_;
    }
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    public java.util.List<? extends edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder> 
        getLandmarksOrBuilderList() {
      return landmarks_;
    }
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    public int getLandmarksCount() {
      return landmarks_.size();
    }
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark getLandmarks(int index) {
      return landmarks_.get(index);
    }
    /**
     * <code>repeated .Landmark landmarks = 2;</code>
     */
    public edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder getLandmarksOrBuilder(
        int index) {
      return landmarks_.get(index);
    }

    // optional .Affordances affs = 3;
    public static final int AFFS_FIELD_NUMBER = 3;
    private edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances affs_;
    /**
     * <code>optional .Affordances affs = 3;</code>
     */
    public boolean hasAffs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Affordances affs = 3;</code>
     */
    public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances getAffs() {
      return affs_;
    }
    /**
     * <code>optional .Affordances affs = 3;</code>
     */
    public edu.usf.ratsim.robot.naorobot.protobuf.Connector.AffordancesOrBuilder getAffsOrBuilder() {
      return affs_;
    }

    private void initFields() {
      ok_ = false;
      landmarks_ = java.util.Collections.emptyList();
      affs_ = edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getLandmarksCount(); i++) {
        if (!getLandmarks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, ok_);
      }
      for (int i = 0; i < landmarks_.size(); i++) {
        output.writeMessage(2, landmarks_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, affs_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      for (int i = 0; i < landmarks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, landmarks_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, affs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.usf.ratsim.robot.naorobot.protobuf.Connector.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response.class, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response.Builder.class);
      }

      // Construct using edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLandmarksFieldBuilder();
          getAffsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ok_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (landmarksBuilder_ == null) {
          landmarks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          landmarksBuilder_.clear();
        }
        if (affsBuilder_ == null) {
          affs_ = edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.getDefaultInstance();
        } else {
          affsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.internal_static_Response_descriptor;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response getDefaultInstanceForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response.getDefaultInstance();
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response build() {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response buildPartial() {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response result = new edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ok_ = ok_;
        if (landmarksBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            landmarks_ = java.util.Collections.unmodifiableList(landmarks_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.landmarks_ = landmarks_;
        } else {
          result.landmarks_ = landmarksBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (affsBuilder_ == null) {
          result.affs_ = affs_;
        } else {
          result.affs_ = affsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response) {
          return mergeFrom((edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response other) {
        if (other == edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response.getDefaultInstance()) return this;
        if (other.hasOk()) {
          setOk(other.getOk());
        }
        if (landmarksBuilder_ == null) {
          if (!other.landmarks_.isEmpty()) {
            if (landmarks_.isEmpty()) {
              landmarks_ = other.landmarks_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLandmarksIsMutable();
              landmarks_.addAll(other.landmarks_);
            }
            onChanged();
          }
        } else {
          if (!other.landmarks_.isEmpty()) {
            if (landmarksBuilder_.isEmpty()) {
              landmarksBuilder_.dispose();
              landmarksBuilder_ = null;
              landmarks_ = other.landmarks_;
              bitField0_ = (bitField0_ & ~0x00000002);
              landmarksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLandmarksFieldBuilder() : null;
            } else {
              landmarksBuilder_.addAllMessages(other.landmarks_);
            }
          }
        }
        if (other.hasAffs()) {
          mergeAffs(other.getAffs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOk()) {
          
          return false;
        }
        for (int i = 0; i < getLandmarksCount(); i++) {
          if (!getLandmarks(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usf.ratsim.robot.naorobot.protobuf.Connector.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool ok = 1;
      private boolean ok_ ;
      /**
       * <code>required bool ok = 1;</code>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }
      /**
       * <code>required bool ok = 1;</code>
       */
      public Builder setOk(boolean value) {
        bitField0_ |= 0x00000001;
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool ok = 1;</code>
       */
      public Builder clearOk() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ok_ = false;
        onChanged();
        return this;
      }

      // repeated .Landmark landmarks = 2;
      private java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark> landmarks_ =
        java.util.Collections.emptyList();
      private void ensureLandmarksIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          landmarks_ = new java.util.ArrayList<edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark>(landmarks_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder, edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder> landmarksBuilder_;

      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark> getLandmarksList() {
        if (landmarksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(landmarks_);
        } else {
          return landmarksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public int getLandmarksCount() {
        if (landmarksBuilder_ == null) {
          return landmarks_.size();
        } else {
          return landmarksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark getLandmarks(int index) {
        if (landmarksBuilder_ == null) {
          return landmarks_.get(index);
        } else {
          return landmarksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public Builder setLandmarks(
          int index, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark value) {
        if (landmarksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLandmarksIsMutable();
          landmarks_.set(index, value);
          onChanged();
        } else {
          landmarksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public Builder setLandmarks(
          int index, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder builderForValue) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          landmarks_.set(index, builderForValue.build());
          onChanged();
        } else {
          landmarksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public Builder addLandmarks(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark value) {
        if (landmarksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLandmarksIsMutable();
          landmarks_.add(value);
          onChanged();
        } else {
          landmarksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public Builder addLandmarks(
          int index, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark value) {
        if (landmarksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLandmarksIsMutable();
          landmarks_.add(index, value);
          onChanged();
        } else {
          landmarksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public Builder addLandmarks(
          edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder builderForValue) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          landmarks_.add(builderForValue.build());
          onChanged();
        } else {
          landmarksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public Builder addLandmarks(
          int index, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder builderForValue) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          landmarks_.add(index, builderForValue.build());
          onChanged();
        } else {
          landmarksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public Builder addAllLandmarks(
          java.lang.Iterable<? extends edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark> values) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          super.addAll(values, landmarks_);
          onChanged();
        } else {
          landmarksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public Builder clearLandmarks() {
        if (landmarksBuilder_ == null) {
          landmarks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          landmarksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public Builder removeLandmarks(int index) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          landmarks_.remove(index);
          onChanged();
        } else {
          landmarksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder getLandmarksBuilder(
          int index) {
        return getLandmarksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder getLandmarksOrBuilder(
          int index) {
        if (landmarksBuilder_ == null) {
          return landmarks_.get(index);  } else {
          return landmarksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public java.util.List<? extends edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder> 
           getLandmarksOrBuilderList() {
        if (landmarksBuilder_ != null) {
          return landmarksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(landmarks_);
        }
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder addLandmarksBuilder() {
        return getLandmarksFieldBuilder().addBuilder(
            edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.getDefaultInstance());
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder addLandmarksBuilder(
          int index) {
        return getLandmarksFieldBuilder().addBuilder(
            index, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.getDefaultInstance());
      }
      /**
       * <code>repeated .Landmark landmarks = 2;</code>
       */
      public java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder> 
           getLandmarksBuilderList() {
        return getLandmarksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder, edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder> 
          getLandmarksFieldBuilder() {
        if (landmarksBuilder_ == null) {
          landmarksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Landmark.Builder, edu.usf.ratsim.robot.naorobot.protobuf.Connector.LandmarkOrBuilder>(
                  landmarks_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          landmarks_ = null;
        }
        return landmarksBuilder_;
      }

      // optional .Affordances affs = 3;
      private edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances affs_ = edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.Builder, edu.usf.ratsim.robot.naorobot.protobuf.Connector.AffordancesOrBuilder> affsBuilder_;
      /**
       * <code>optional .Affordances affs = 3;</code>
       */
      public boolean hasAffs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Affordances affs = 3;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances getAffs() {
        if (affsBuilder_ == null) {
          return affs_;
        } else {
          return affsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Affordances affs = 3;</code>
       */
      public Builder setAffs(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances value) {
        if (affsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          affs_ = value;
          onChanged();
        } else {
          affsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Affordances affs = 3;</code>
       */
      public Builder setAffs(
          edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.Builder builderForValue) {
        if (affsBuilder_ == null) {
          affs_ = builderForValue.build();
          onChanged();
        } else {
          affsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Affordances affs = 3;</code>
       */
      public Builder mergeAffs(edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances value) {
        if (affsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              affs_ != edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.getDefaultInstance()) {
            affs_ =
              edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.newBuilder(affs_).mergeFrom(value).buildPartial();
          } else {
            affs_ = value;
          }
          onChanged();
        } else {
          affsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Affordances affs = 3;</code>
       */
      public Builder clearAffs() {
        if (affsBuilder_ == null) {
          affs_ = edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.getDefaultInstance();
          onChanged();
        } else {
          affsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Affordances affs = 3;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.Builder getAffsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAffsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Affordances affs = 3;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.Connector.AffordancesOrBuilder getAffsOrBuilder() {
        if (affsBuilder_ != null) {
          return affsBuilder_.getMessageOrBuilder();
        } else {
          return affs_;
        }
      }
      /**
       * <code>optional .Affordances affs = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.Builder, edu.usf.ratsim.robot.naorobot.protobuf.Connector.AffordancesOrBuilder> 
          getAffsFieldBuilder() {
        if (affsBuilder_ == null) {
          affsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances, edu.usf.ratsim.robot.naorobot.protobuf.Connector.Affordances.Builder, edu.usf.ratsim.robot.naorobot.protobuf.Connector.AffordancesOrBuilder>(
                  affs_,
                  getParentForChildren(),
                  isClean());
          affs_ = null;
        }
        return affsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Command_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Landmark_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Landmark_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Affordances_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Affordances_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017connector.proto\"\232\001\n\007Command\022+\n\004type\030\001 " +
      "\001(\0162\024.Command.CommandType:\007getInfo\022\r\n\005an" +
      "gle\030\002 \001(\002\"S\n\013CommandType\022\014\n\010doAction\020\000\022\n" +
      "\n\006rotate\020\001\022\013\n\007getInfo\020\002\022\016\n\nstartRobot\020\003\022" +
      "\r\n\tstopRobot\020\004\"7\n\010Landmark\022\n\n\002id\030\001 \002(\005\022\t" +
      "\n\001x\030\002 \002(\002\022\t\n\001y\030\003 \002(\002\022\t\n\001z\030\004 \002(\002\"\032\n\013Affor" +
      "dances\022\013\n\003aff\030\001 \003(\010\"P\n\010Response\022\n\n\002ok\030\001 " +
      "\002(\010\022\034\n\tlandmarks\030\002 \003(\0132\t.Landmark\022\032\n\004aff" +
      "s\030\003 \001(\0132\014.AffordancesB(\n&edu.usf.ratsim." +
      "robot.naorobot.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Command_descriptor,
              new java.lang.String[] { "Type", "Angle", });
          internal_static_Landmark_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Landmark_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Landmark_descriptor,
              new java.lang.String[] { "Id", "X", "Y", "Z", });
          internal_static_Affordances_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Affordances_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Affordances_descriptor,
              new java.lang.String[] { "Aff", });
          internal_static_Response_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Response_descriptor,
              new java.lang.String[] { "Ok", "Landmarks", "Affs", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
