// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_robocup_ssl_refbox_log.proto

package edu.usf.ratsim.robot.naorobot.protobuf;

public final class MessagesRobocupSslRefboxLog {
  private MessagesRobocupSslRefboxLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Log_FrameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .SSL_DetectionFrame frame = 1;
    /**
     * <code>required .SSL_DetectionFrame frame = 1;</code>
     */
    boolean hasFrame();
    /**
     * <code>required .SSL_DetectionFrame frame = 1;</code>
     */
    edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame getFrame();
    /**
     * <code>required .SSL_DetectionFrame frame = 1;</code>
     */
    edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getFrameOrBuilder();

    // required string refbox_cmd = 2;
    /**
     * <code>required string refbox_cmd = 2;</code>
     */
    boolean hasRefboxCmd();
    /**
     * <code>required string refbox_cmd = 2;</code>
     */
    java.lang.String getRefboxCmd();
    /**
     * <code>required string refbox_cmd = 2;</code>
     */
    com.google.protobuf.ByteString
        getRefboxCmdBytes();
  }
  /**
   * Protobuf type {@code Log_Frame}
   */
  public static final class Log_Frame extends
      com.google.protobuf.GeneratedMessage
      implements Log_FrameOrBuilder {
    // Use Log_Frame.newBuilder() to construct.
    private Log_Frame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Log_Frame(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Log_Frame defaultInstance;
    public static Log_Frame getDefaultInstance() {
      return defaultInstance;
    }

    public Log_Frame getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Log_Frame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = frame_.toBuilder();
              }
              frame_ = input.readMessage(edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(frame_);
                frame_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              refboxCmd_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Log_Frame_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Log_Frame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.class, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.class);
    }

    public static com.google.protobuf.Parser<Log_Frame> PARSER =
        new com.google.protobuf.AbstractParser<Log_Frame>() {
      public Log_Frame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Log_Frame(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Log_Frame> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .SSL_DetectionFrame frame = 1;
    public static final int FRAME_FIELD_NUMBER = 1;
    private edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame frame_;
    /**
     * <code>required .SSL_DetectionFrame frame = 1;</code>
     */
    public boolean hasFrame() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .SSL_DetectionFrame frame = 1;</code>
     */
    public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame getFrame() {
      return frame_;
    }
    /**
     * <code>required .SSL_DetectionFrame frame = 1;</code>
     */
    public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getFrameOrBuilder() {
      return frame_;
    }

    // required string refbox_cmd = 2;
    public static final int REFBOX_CMD_FIELD_NUMBER = 2;
    private java.lang.Object refboxCmd_;
    /**
     * <code>required string refbox_cmd = 2;</code>
     */
    public boolean hasRefboxCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string refbox_cmd = 2;</code>
     */
    public java.lang.String getRefboxCmd() {
      java.lang.Object ref = refboxCmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          refboxCmd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string refbox_cmd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRefboxCmdBytes() {
      java.lang.Object ref = refboxCmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refboxCmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      frame_ = edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
      refboxCmd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFrame()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRefboxCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFrame().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, frame_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRefboxCmdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, frame_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRefboxCmdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Log_Frame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Log_Frame_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Log_Frame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.class, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder.class);
      }

      // Construct using edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFrameFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (frameBuilder_ == null) {
          frame_ = edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
        } else {
          frameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        refboxCmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Log_Frame_descriptor;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame getDefaultInstanceForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance();
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame build() {
        edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame buildPartial() {
        edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame result = new edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (frameBuilder_ == null) {
          result.frame_ = frame_;
        } else {
          result.frame_ = frameBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.refboxCmd_ = refboxCmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame) {
          return mergeFrom((edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame other) {
        if (other == edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance()) return this;
        if (other.hasFrame()) {
          mergeFrame(other.getFrame());
        }
        if (other.hasRefboxCmd()) {
          bitField0_ |= 0x00000002;
          refboxCmd_ = other.refboxCmd_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFrame()) {
          
          return false;
        }
        if (!hasRefboxCmd()) {
          
          return false;
        }
        if (!getFrame().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .SSL_DetectionFrame frame = 1;
      private edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame frame_ = edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> frameBuilder_;
      /**
       * <code>required .SSL_DetectionFrame frame = 1;</code>
       */
      public boolean hasFrame() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .SSL_DetectionFrame frame = 1;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame getFrame() {
        if (frameBuilder_ == null) {
          return frame_;
        } else {
          return frameBuilder_.getMessage();
        }
      }
      /**
       * <code>required .SSL_DetectionFrame frame = 1;</code>
       */
      public Builder setFrame(edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame value) {
        if (frameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          frame_ = value;
          onChanged();
        } else {
          frameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .SSL_DetectionFrame frame = 1;</code>
       */
      public Builder setFrame(
          edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder builderForValue) {
        if (frameBuilder_ == null) {
          frame_ = builderForValue.build();
          onChanged();
        } else {
          frameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .SSL_DetectionFrame frame = 1;</code>
       */
      public Builder mergeFrame(edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame value) {
        if (frameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              frame_ != edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance()) {
            frame_ =
              edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder(frame_).mergeFrom(value).buildPartial();
          } else {
            frame_ = value;
          }
          onChanged();
        } else {
          frameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .SSL_DetectionFrame frame = 1;</code>
       */
      public Builder clearFrame() {
        if (frameBuilder_ == null) {
          frame_ = edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
          onChanged();
        } else {
          frameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .SSL_DetectionFrame frame = 1;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder getFrameBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFrameFieldBuilder().getBuilder();
      }
      /**
       * <code>required .SSL_DetectionFrame frame = 1;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getFrameOrBuilder() {
        if (frameBuilder_ != null) {
          return frameBuilder_.getMessageOrBuilder();
        } else {
          return frame_;
        }
      }
      /**
       * <code>required .SSL_DetectionFrame frame = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> 
          getFrameFieldBuilder() {
        if (frameBuilder_ == null) {
          frameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder>(
                  frame_,
                  getParentForChildren(),
                  isClean());
          frame_ = null;
        }
        return frameBuilder_;
      }

      // required string refbox_cmd = 2;
      private java.lang.Object refboxCmd_ = "";
      /**
       * <code>required string refbox_cmd = 2;</code>
       */
      public boolean hasRefboxCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string refbox_cmd = 2;</code>
       */
      public java.lang.String getRefboxCmd() {
        java.lang.Object ref = refboxCmd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          refboxCmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string refbox_cmd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRefboxCmdBytes() {
        java.lang.Object ref = refboxCmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          refboxCmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string refbox_cmd = 2;</code>
       */
      public Builder setRefboxCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        refboxCmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string refbox_cmd = 2;</code>
       */
      public Builder clearRefboxCmd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        refboxCmd_ = getDefaultInstance().getRefboxCmd();
        onChanged();
        return this;
      }
      /**
       * <code>required string refbox_cmd = 2;</code>
       */
      public Builder setRefboxCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        refboxCmd_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Log_Frame)
    }

    static {
      defaultInstance = new Log_Frame(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Log_Frame)
  }

  public interface Refbox_LogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Log_Frame log = 1;
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame> 
        getLogList();
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame getLog(int index);
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    int getLogCount();
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    java.util.List<? extends edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> 
        getLogOrBuilderList();
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder getLogOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Refbox_Log}
   */
  public static final class Refbox_Log extends
      com.google.protobuf.GeneratedMessage
      implements Refbox_LogOrBuilder {
    // Use Refbox_Log.newBuilder() to construct.
    private Refbox_Log(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Refbox_Log(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Refbox_Log defaultInstance;
    public static Refbox_Log getDefaultInstance() {
      return defaultInstance;
    }

    public Refbox_Log getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Refbox_Log(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                log_ = new java.util.ArrayList<edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame>();
                mutable_bitField0_ |= 0x00000001;
              }
              log_.add(input.readMessage(edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          log_ = java.util.Collections.unmodifiableList(log_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.class, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.class);
    }

    public static com.google.protobuf.Parser<Refbox_Log> PARSER =
        new com.google.protobuf.AbstractParser<Refbox_Log>() {
      public Refbox_Log parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Refbox_Log(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Refbox_Log> getParserForType() {
      return PARSER;
    }

    // repeated .Log_Frame log = 1;
    public static final int LOG_FIELD_NUMBER = 1;
    private java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame> log_;
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    public java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame> getLogList() {
      return log_;
    }
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    public java.util.List<? extends edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> 
        getLogOrBuilderList() {
      return log_;
    }
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    public int getLogCount() {
      return log_.size();
    }
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame getLog(int index) {
      return log_.get(index);
    }
    /**
     * <code>repeated .Log_Frame log = 1;</code>
     */
    public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder getLogOrBuilder(
        int index) {
      return log_.get(index);
    }

    private void initFields() {
      log_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getLogCount(); i++) {
        if (!getLog(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < log_.size(); i++) {
        output.writeMessage(1, log_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < log_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, log_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Refbox_Log}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.class, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.Builder.class);
      }

      // Construct using edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLogFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (logBuilder_ == null) {
          log_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          logBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_descriptor;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log getDefaultInstanceForType() {
        return edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstance();
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log build() {
        edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log buildPartial() {
        edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log result = new edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log(this);
        int from_bitField0_ = bitField0_;
        if (logBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            log_ = java.util.Collections.unmodifiableList(log_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.log_ = log_;
        } else {
          result.log_ = logBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log) {
          return mergeFrom((edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log other) {
        if (other == edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstance()) return this;
        if (logBuilder_ == null) {
          if (!other.log_.isEmpty()) {
            if (log_.isEmpty()) {
              log_ = other.log_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLogIsMutable();
              log_.addAll(other.log_);
            }
            onChanged();
          }
        } else {
          if (!other.log_.isEmpty()) {
            if (logBuilder_.isEmpty()) {
              logBuilder_.dispose();
              logBuilder_ = null;
              log_ = other.log_;
              bitField0_ = (bitField0_ & ~0x00000001);
              logBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLogFieldBuilder() : null;
            } else {
              logBuilder_.addAllMessages(other.log_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getLogCount(); i++) {
          if (!getLog(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Refbox_Log) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Log_Frame log = 1;
      private java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame> log_ =
        java.util.Collections.emptyList();
      private void ensureLogIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          log_ = new java.util.ArrayList<edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame>(log_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> logBuilder_;

      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame> getLogList() {
        if (logBuilder_ == null) {
          return java.util.Collections.unmodifiableList(log_);
        } else {
          return logBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public int getLogCount() {
        if (logBuilder_ == null) {
          return log_.size();
        } else {
          return logBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame getLog(int index) {
        if (logBuilder_ == null) {
          return log_.get(index);
        } else {
          return logBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public Builder setLog(
          int index, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogIsMutable();
          log_.set(index, value);
          onChanged();
        } else {
          logBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public Builder setLog(
          int index, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.set(index, builderForValue.build());
          onChanged();
        } else {
          logBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public Builder addLog(edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogIsMutable();
          log_.add(value);
          onChanged();
        } else {
          logBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public Builder addLog(
          int index, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogIsMutable();
          log_.add(index, value);
          onChanged();
        } else {
          logBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public Builder addLog(
          edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.add(builderForValue.build());
          onChanged();
        } else {
          logBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public Builder addLog(
          int index, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.add(index, builderForValue.build());
          onChanged();
        } else {
          logBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public Builder addAllLog(
          java.lang.Iterable<? extends edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame> values) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          super.addAll(values, log_);
          onChanged();
        } else {
          logBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public Builder clearLog() {
        if (logBuilder_ == null) {
          log_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          logBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public Builder removeLog(int index) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.remove(index);
          onChanged();
        } else {
          logBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder getLogBuilder(
          int index) {
        return getLogFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder getLogOrBuilder(
          int index) {
        if (logBuilder_ == null) {
          return log_.get(index);  } else {
          return logBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public java.util.List<? extends edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> 
           getLogOrBuilderList() {
        if (logBuilder_ != null) {
          return logBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(log_);
        }
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder addLogBuilder() {
        return getLogFieldBuilder().addBuilder(
            edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance());
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder addLogBuilder(
          int index) {
        return getLogFieldBuilder().addBuilder(
            index, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance());
      }
      /**
       * <code>repeated .Log_Frame log = 1;</code>
       */
      public java.util.List<edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder> 
           getLogBuilderList() {
        return getLogFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> 
          getLogFieldBuilder() {
        if (logBuilder_ == null) {
          logBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_Frame.Builder, edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslRefboxLog.Log_FrameOrBuilder>(
                  log_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          log_ = null;
        }
        return logBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Refbox_Log)
    }

    static {
      defaultInstance = new Refbox_Log(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Refbox_Log)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Log_Frame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Log_Frame_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Refbox_Log_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Refbox_Log_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%messages_robocup_ssl_refbox_log.proto\032" +
      "$messages_robocup_ssl_detection.proto\"C\n" +
      "\tLog_Frame\022\"\n\005frame\030\001 \002(\0132\023.SSL_Detectio" +
      "nFrame\022\022\n\nrefbox_cmd\030\002 \002(\t\"%\n\nRefbox_Log" +
      "\022\027\n\003log\030\001 \003(\0132\n.Log_FrameB(\n&edu.usf.rat" +
      "sim.robot.naorobot.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Log_Frame_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Log_Frame_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Log_Frame_descriptor,
              new java.lang.String[] { "Frame", "RefboxCmd", });
          internal_static_Refbox_Log_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Refbox_Log_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Refbox_Log_descriptor,
              new java.lang.String[] { "Log", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.usf.ratsim.robot.naorobot.protobuf.MessagesRobocupSslDetection.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
